version: '3'

services:
  frontend:
    build: ./client
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - REACT_APP_FRONTEND_PORT=${FRONTEND_PORT}
      - REACT_APP_BACKEND_PORT=${BACKEND_PORT}
    networks:
      - my-network
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      - FLASK_ENV=production
      - BACKEND_PORT=${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - my-network
    restart: always
networks:
  my-network:
    driver: bridge