version: '3'

services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5050
    networks:
      - my-network
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      - FLASK_ENV=production
      - REACT_APP_BACKEND_PORT=5000
    ports:
      - "5050:5050"
    networks:
      - my-network
    restart: always
networks:
  my-network:
    driver: bridge