---
psswd_names:
- psswd
- password
- pwd
salt_names:
- salt
- slt
bad_algorithms:
  sha_2:
    reason: well-known vulnerabilities with SHA-2 based hash functions
packages:
  flask_security: {}
  argon2:
    hashobj:
      PasswordHasher:
        hashes:
          pwinput: incall
          message_digest: hash
          iteration: false
          keylen: false
          algorithm: argon
  bcrypt:
    hashobj:
      hashpw:
        hashes:
          pwinput: incall
          message_digest: incall
          iteration: false
          keylen: false
          algorithm: bcrypt
    saltobj:
      gensalt:
        salts:
          salt_digest: incall
  hashlib:
    hashobj:
      new:
        hashes:
          pwinput: update
          message_digest:
          - digest
          - hexdigest
          iteration: false
          keylen: false
          algorithm:
          - md4
          - sha3_384
          - sha512
          - md5-sha1
          - sha256
          - sha512_224
          - sha3_256
          - sm3
          - ripemd160
          - shake_256
          - sha384
          - sha512_256
          - sha3_512
          - mdc2
          - sha224
          - blake2b
          - sha3_224
          - md5
          - blake2s
          - sha1
          - shake_128
          - whirlpool
      pbkdf2_hmac:
        hashes:
          pwinput: incall
          message_digest: incall
          iterations: true
          keylen: true
          algorithm:
          - md4
          - sha3_384
          - sha512
          - md5-sha1
          - sha256
          - sha512_224
          - sha3_256
          - sm3
          - ripemd160
          - shake_256
          - sha384
          - sha512_256
          - sha3_512
          - mdc2
          - sha224
          - blake2b
          - sha3_224
          - md5
          - blake2s
          - sha1
          - shake_128
          - whirlpool
      md5:
        hashes:
          pwinput: incall
          message_digest:
          - message_digest
          - hexmessage_digest
          iteration: false
          keylen: false
          algorithm: md5
      sha256:
        hashes:
          pwinput: incall
          message_digest:
          - message_digest
          - hexmessage_digest
          algorithm: sha256
      sha1:
        hashes:
          pwinput: incall
          message_digest:
          - message_digest
          - hexmessage_digest
          iteration: false
          keylen: false
          algorithm: sha1
      sha512:
        hashes:
          pwinput: incall
          message_digest:
          - message_digest
          - hexmessage_digest
          iteration: false
          keylen: false
          algorithm: sha512
      sha384:
        hashes:
          pwinput: incall
          message_digest:
          - message_digest
          - hexmessage_digest
          iteration: false
          keylen: false
          algorithm: sha384
      sha224:
        hashes:
          pwinput: incall
          message_digest:
          - message_digest
          - hexmessage_digest
          iteration: false
          keylen: false
          algorithm: sha224
  werkzeug.security:
    hashobj:
      pbkdf2_hex:
        hashes:
          pwinput: incall
          message_digest: incall
          iterations: true
          keylen: true
          algorithm:
          - md4
          - sha3_384
          - sha512
          - md5-sha1
          - sha256
          - sha512_224
          - sha3_256
          - sm3
          - ripemd160
          - shake_256
          - sha384
          - sha512_256
          - sha3_512
          - mdc2
          - sha224
          - blake2b
          - sha3_224
          - md5
          - blake2s
          - sha1
          - shake_128
          - whirlpool
      pbkdf2_bin:
        hashes:
          pwinput: incall
          message_digest: incall
          iteration: true
          keylen: true
          algorithm:
          - md4
          - sha3_384
          - sha512
          - md5-sha1
          - sha256
          - sha512_224
          - sha3_256
          - sm3
          - ripemd160
          - shake_256
          - sha384
          - sha512_256
          - sha3_512
          - mdc2
          - sha224
          - blake2b
          - sha3_224
          - md5
          - blake2s
          - sha1
          - shake_128
          - whirlpool